"""Regenerate the private symbol header after updating vendored libwebp.

The extra names are globals without an upstream namespace, audited with llvm-nm
on the combined webp, demux, mux and SharpYUV archives. Audit again after upgrades.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[2]
dest = root / "src/formats/libwebp"
extra = '''ChunkAppend ChunkAssignData ChunkDelete ChunkGetIdFromTag ChunkGetIndexFromFourCC ChunkGetIndexFromTag ChunkGetTagFromFourCC ChunkInit ChunkListDelete ChunkListDiskSize ChunkListEmit ChunkRelease ChunkSearchList ChunkSetHead GetColorPalette IsValidColorspace kChunks kLog2Table kPrefixEncodeCode kPrefixEncodeExtraBitsValue kSLog2Table kVP8Log2Range kVP8NewRange MuxEmitRiffHeader MuxGetChunkListFromId MuxHasAlpha MuxImageCount MuxImageDelete MuxImageDeleteNth MuxImageDiskSize MuxImageEmit MuxImageFinalize MuxImageGetNth MuxImageInit MuxImagePush MuxImageRelease MuxValidate PaletteSort PrepareMapToPalette QuantizeLevels ReadHuffmanCodesHelper SearchColorNoIdx'''.split()

names = set(extra)
macros = set()
for path in sorted(dest.rglob("*")):
    if path.suffix in (".h", ".c"):
        source = path.read_text(encoding="utf-8")
        names.update(re.findall(r"\b(?:WebP|VP8|SharpYuv|InitSharpYuv)[A-Za-z0-9_]*\b", source))
        macros.update(re.findall(r"^\s*#\s*define\s+(\w+)", source, re.M))
names.difference_update(macros)
header = """// Private libwebp 1.6.0 symbols, including SIMD variants and SharpYUV.
// Generated by scripts/dev/generate-webp-symbols.py. Do not edit manually.
#pragma once

// SharpYUV already aliases this name to its own CPU-info variable.
#ifndef PATCHY_WEBP_SHARPYUV_BUILD
#define VP8GetCPUInfo patchy_webp_VP8GetCPUInfo
#endif

#ifndef WEBP_REDUCE_CSP
"""
for name in ["Rgb", "Bgr", "Argb", "Rgba4444", "Rgb565"]:
    header += f"#define WebPYuv444To{name}_C patchy_webp_WebPYuv444To{name}_C\n"
header += """#endif

"""
header += "".join(f"#define {name} patchy_webp_{name}\n" for name in sorted(names))
(root / "src/formats/webp_symbols.hpp").write_text(header, encoding="utf-8")
