# Pinned, private codec. No tools, system codec discovery, or runtime DLLs.
function(patchy_add_webp)
  set(BUILD_SHARED_LIBS OFF)
  set(WEBP_LINK_STATIC ON)
  set(WEBP_USE_THREAD OFF)
  foreach(option ANIM_UTILS CWEBP DWEBP GIF2WEBP IMG2WEBP VWEBP WEBPINFO WEBPMUX EXTRAS WEBP_JS FUZZTEST)
    set(WEBP_BUILD_${option} OFF)
  endforeach()
  set(WEBP_BUILD_LIBWEBPMUX ON)
  add_subdirectory(src/formats/libwebp EXCLUDE_FROM_ALL)
  target_compile_definitions(sharpyuv PRIVATE PATCHY_WEBP_SHARPYUV_BUILD=1)
  get_property(codec_targets DIRECTORY "${PROJECT_SOURCE_DIR}/src/formats/libwebp" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS codec_targets)
    if(MSVC)
      target_compile_options(${target} PRIVATE "/FI${PROJECT_SOURCE_DIR}/src/formats/webp_symbols.hpp")
    else()
      target_compile_options(${target} PRIVATE "-include" "${PROJECT_SOURCE_DIR}/src/formats/webp_symbols.hpp")
    endif()
  endforeach()
endfunction()
patchy_add_webp()
