# Writes the generated build-stamp header with the build machine's current
# local wall clock. The patchy_build_stamp custom target runs this with
# cmake -P on every build (a custom target is always out of date), so the
# binary can never carry an earlier build's date the way a TU-local
# __DATE__/__TIME__ could once incremental builds reuse the object file.
if(NOT PATCHY_BUILD_STAMP_HEADER)
  message(FATAL_ERROR "PATCHY_BUILD_STAMP_HEADER was not passed with -D.")
endif()
string(TIMESTAMP PATCHY_BUILD_STAMP_NOW "%Y-%m-%d %H:%M")
file(WRITE "${PATCHY_BUILD_STAMP_HEADER}" "#pragma once

// Generated by cmake/write_build_stamp.cmake on every build; never edit or
// commit. Include it only from build_info.cpp: every includer recompiles on
// every build.
#define PATCHY_BUILD_STAMP \"${PATCHY_BUILD_STAMP_NOW}\"
")
