"""Generates src/psd/psd_text_engine_template.cpp from a Photoshop 2026 Txt2 block.

The template is the DocumentResources and DocumentObjects boilerplate Patchy cannot invent
(Kinsoku and MojiKumi sets, the quote table, the predefined list styles, the default style and
paragraph sheets, the story record), with every per-document part emptied: no text objects,
no frames, and a FontSet of just AdobeInvisFont plus MyriadPro-Regular (index 1, the default
sheets' font). See docs/txt2.md.

  python scripts/dev/txt2/make_template.py <photoshop-authored.psd> [out.cpp]
"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import txt2tool as T


def main(argv):
    src = argv[1]
    out = argv[2] if len(argv) > 2 else os.path.join(os.path.dirname(__file__), '..', '..', '..', 'src', 'psd',
                                                     'psd_text_engine_template.cpp')
    b, body, root = T.load_root(src)
    if root is None:
        raise SystemExit('no Txt2 block in ' + src)
    resources = T.get(root, '0')
    objects_root = T.get(root, '1')

    # FontSet: keep AdobeInvisFont and the Myriad default; drop every document font.
    fonts = T.get(resources, '1', '0')
    keep = []
    for entry in fonts.items:
        name = T.scalar_text(T.get(entry, '0', '0', '0').raw)
        if name in ('S:AdobeInvisFont', 'S:MyriadPro-Regular'):
            keep.append((name, entry))
    keep.sort(key=lambda pair: 0 if pair[0] == 'S:AdobeInvisFont' else 1)
    fonts.items = [entry for _, entry in keep]
    assert len(fonts.items) == 2, [n for n, _ in keep]
    # Default sheets point at the Myriad entry (index 1).
    for sheet_path in (('0', '5', '0', '0', '0', '6'), ('1', '2')):
        sheet = T.get(root, *sheet_path)
        T.set_item(sheet, '0', T.scalar(1))
    basic = T.get(root, '0', '6', '0')
    for entry in basic.items:
        style = dict(T.get(entry, '0').items).get('5')
        if style is not None and dict(style.items).get('32') is not None and dict(T.get(style, '32').items):
            T.set_item(T.get(style, '32'), '0', T.scalar(1))
    # No frames, no objects; the story keeps its bit strings and loses its font versions.
    T.set_item(T.get(resources, '8'), '0', T.mklist([]))
    T.set_item(objects_root, '1', T.mklist([]))
    story = T.get(objects_root, '5')
    for entry in story.items:
        if dict(entry.items).get('4') is not None:
            T.set_item(entry, '4', T.mklist([]))
    data = T.body_bytes(root)

    lines = []
    lines.append('// Generated by scripts/dev/txt2/make_template.py from a Photoshop 2026 Txt2 block.')
    lines.append('// The document-level text engine boilerplate Patchy authors its own text objects into;')
    lines.append('// see docs/txt2.md. Do not edit by hand.')
    lines.append('')
    lines.append('#include "psd/psd_text_engine_block.hpp"')
    lines.append('')
    lines.append('namespace patchy::psd {')
    lines.append('')
    lines.append('namespace {')
    lines.append('')
    lines.append('constexpr unsigned char kTextEngineTemplate[] = {')
    row = []
    for i, byte in enumerate(data):
        row.append('0x%02x,' % byte)
        if len(row) == 24:
            lines.append('    ' + ' '.join(row))
            row = []
    if row:
        lines.append('    ' + ' '.join(row))
    lines.append('};')
    lines.append('')
    lines.append('}  // namespace')
    lines.append('')
    lines.append('std::span<const std::uint8_t> text_engine_template_bytes() {')
    lines.append('  return std::span<const std::uint8_t>(kTextEngineTemplate, sizeof(kTextEngineTemplate));')
    lines.append('}')
    lines.append('')
    lines.append('}  // namespace patchy::psd')
    lines.append('')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print('wrote', os.path.normpath(out), len(data), 'bytes of template')


if __name__ == '__main__':
    main(sys.argv)
