# Regenerates the README marketing screenshots.
#
# Two pipelines (docs/testing.md "README screenshots"):
#
# 1. Script-driven scenes ($jsScenes below): a fresh unattended patchy.exe runs a
#    scripts\dev\readme-shots\*.js scene through --run-script on the REAL windows
#    platform, so every installed font renders (the offscreen platform enumerates
#    none). The app window appears on screen for a few seconds per scene; the
#    capture itself never raises or focuses it. PATCHY_SETTINGS_DIR isolates the
#    run from the user's real Patchy settings (recent files, window geometry),
#    PATCHY_NO_SINGLE_INSTANCE=1 keeps it out of any running instance, and the
#    DPI pins keep shots at their logical size on scaled monitors.
#
# 2. Offscreen test scenes (everything else): the shot_readme_* scenes in
#    patchy_ui_visual_tests run offscreen and their PNGs are copied out of
#    test-artifacts/. These migrate to pipeline 1 over time; the test scenes
#    stay in the suite as regression smoke tests either way.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\make-readme-screenshots.ps1 [-SkipBuild] [-Scene camera_raw]
#
# Some scenes need local fixtures (not committed): akiko_cycling_okinawa.jpg,
# ipad_main_v04.psd, mow_master.psd in local-test-fixtures/psd/, the Camera Raw
# scene's local-test-fixtures/raw/fujifilm_xt1.raf (CC0, raw.pixls.us). Scenes whose
# fixture is missing are skipped with a [SKIP] line.
param(
    [switch]$SkipBuild,
    [ValidatePattern('^[a-z0-9_]+$')][string]$Scene = 'shot_readme',
    [switch]$IncludeLegacyPlugins
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $repo 'docs\images\screenshots'
$buildDir = Join-Path $repo 'build\release'

# DWM rounds every window Patchy frames itself, but it clips in the compositor
# (src/ui/window_effects.cpp, DWMWCP_ROUND), so a grabbed window is square. The
# offscreen scenes get their corners in save_readme_shot; script-driven scenes capture
# through the app's own patchy.ui.captureWindow, so they get them here. Keep the radius
# in step with kReadmeWindowCornerRadius in tests/ui/readme_screenshot_test_support.hpp.
function Set-RoundedWindowCorners {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [int]$Radius = 8
    )
    Add-Type -AssemblyName System.Drawing
    # Read through a MemoryStream: Bitmap::FromFile would hold the file open and the
    # rounded copy has to be written back over it.
    $stream = New-Object System.IO.MemoryStream(, [System.IO.File]::ReadAllBytes($Path))
    try {
        $source = [System.Drawing.Bitmap]::FromStream($stream)
        try {
            $rounded = New-Object System.Drawing.Bitmap(
                $source.Width, $source.Height, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
            try {
                $graphics = [System.Drawing.Graphics]::FromImage($rounded)
                $shape = New-Object System.Drawing.Drawing2D.GraphicsPath
                $brush = New-Object System.Drawing.TextureBrush($source)
                try {
                    $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
                    $graphics.Clear([System.Drawing.Color]::Transparent)
                    $diameter = $Radius * 2
                    $shape.AddArc(0, 0, $diameter, $diameter, 180, 90)
                    $shape.AddArc($source.Width - $diameter, 0, $diameter, $diameter, 270, 90)
                    $shape.AddArc($source.Width - $diameter, $source.Height - $diameter, $diameter, $diameter, 0, 90)
                    $shape.AddArc(0, $source.Height - $diameter, $diameter, $diameter, 90, 90)
                    $shape.CloseFigure()
                    # FillPath honors SmoothingMode; SetClip would give hard-edged
                    # aliased corners instead, because GDI+ regions are not antialiased.
                    $graphics.FillPath($brush, $shape)
                } finally {
                    $brush.Dispose()
                    $shape.Dispose()
                    $graphics.Dispose()
                }
                $rounded.Save($Path, [System.Drawing.Imaging.ImageFormat]::Png)
            } finally {
                $rounded.Dispose()
            }
        } finally {
            $source.Dispose()
        }
    } finally {
        $stream.Dispose()
    }
}

# Scenes generated by driving the real app through the scripting CLI.
# Key = the README image base name; Script = the scene; Args = extra
# --script-arg tokens; Fixture = skip the scene when this file is missing.
$jsScenes = [ordered]@{
    'plugin_kpt5' = @{
        Script = Join-Path $repo 'scripts\dev\readme-shots\plugin-kpt5.js'
        Args = @("photo=$(Join-Path $repo 'test-fixtures\readme\san_francisco_cityscape_cc0.jpg')")
        Fixture = Join-Path $repo 'local-test-fixtures\photoshop-plugins\kpt5\KPT5_Files\KPT5'
        Legacy = $true
    }
}

# The hero uses the Smart Filters image directly. Retired gallery scenes stay
# available as regression tests, but must not republish removed PNGs.
if ($Scene -eq 'hero' -or $Scene -eq 'shot_readme_hero') { $Scene = 'smart_filters' }
$retiredScenes = @('levels', 'brush_dynamics', 'shape_appearance', 'affinity_import')
$sceneName = $Scene -replace '^shot_readme_?', ''
if ($retiredScenes -contains $sceneName) {
    throw "$sceneName is retired from the gallery; see docs/readme-showcase.md for the consolidated scenes"
}
$runAll = [string]::IsNullOrEmpty($sceneName)
$jsToRun = @()
if ($runAll) {
    $jsToRun = @($jsScenes.Keys | Where-Object { -not $jsScenes[$_].Legacy -or $IncludeLegacyPlugins })
    if (-not $IncludeLegacyPlugins) { Write-Host '[SKIP] plugin_kpt5 (use -IncludeLegacyPlugins or -Scene plugin_kpt5)' }
} elseif ($jsScenes.Contains($sceneName)) {
    $jsToRun = @($sceneName)
}
$runOffscreen = $runAll -or -not $jsScenes.Contains($sceneName)

if (-not $SkipBuild) {
    Push-Location $repo
    try {
        cmd /s /c 'scripts\vs-env.bat -arch=x64 -host_arch=x64 >nul && scripts\run-throttled.bat "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --build --preset release -j 20 --target patchy patchy_ui_visual_tests'
        if ($LASTEXITCODE -ne 0) { throw "build failed (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
    }
}
New-Item -ItemType Directory -Force $outDir | Out-Null

# --- Pipeline 2: offscreen test scenes -------------------------------------
if ($runOffscreen) {
    $exe = Join-Path $buildDir 'patchy_ui_visual_tests.exe'
    if (-not (Test-Path $exe)) { throw "missing $exe (run without -SkipBuild)" }
    $filter = if ($Scene.StartsWith('shot_readme')) { $Scene } else { "shot_readme_$Scene" }
    $artifactPattern = "$filter*.png"
    $artifactDir = Join-Path $buildDir 'test-artifacts'
    if (Test-Path $artifactDir) {
        Get-ChildItem (Join-Path $artifactDir $artifactPattern) -ErrorAction SilentlyContinue |
            Remove-Item -Force
    }

    $oldPlatform = $env:QT_QPA_PLATFORM
    $oldSound = $env:PATCHY_NO_SOUND
    $testLog = Join-Path $buildDir "readme-shot-$filter.log"
    Push-Location $buildDir
    try {
        $env:QT_QPA_PLATFORM = 'offscreen'
        $env:PATCHY_NO_SOUND = '1'
        & (Join-Path $repo 'scripts\run-throttled.bat') $exe $filter | Tee-Object -FilePath $testLog
        if ($LASTEXITCODE -ne 0 -or (Select-String -LiteralPath $testLog -Pattern '^\[FAIL\]' -Quiet)) {
            throw "screenshot scenes failed (exit $LASTEXITCODE); see $testLog"
        }
    } finally {
        Pop-Location
        $env:QT_QPA_PLATFORM = $oldPlatform
        $env:PATCHY_NO_SOUND = $oldSound
    }

    $shots = @(Get-ChildItem (Join-Path $artifactDir $artifactPattern) -ErrorAction SilentlyContinue)
    if ($shots.Count -eq 0 -and $jsToRun.Count -eq 0) { throw "no $artifactPattern artifacts were produced" }
    foreach ($shot in $shots) {
        $name = $shot.Name -replace '^shot_readme_', ''
        if ($retiredScenes -contains [System.IO.Path]::GetFileNameWithoutExtension($name)) { continue }
        if ($jsScenes.Contains([System.IO.Path]::GetFileNameWithoutExtension($name))) {
            continue  # migrated scene: the script-driven pipeline owns this image
        }
        $dest = Join-Path $outDir $name
        Copy-Item $shot.FullName $dest -Force
        Write-Host "updated $dest"
    }
}

# --- Pipeline 1: script-driven scenes (real app, real fonts) ----------------
foreach ($name in $jsToRun) {
    # NOT $scene: PowerShell variables are case-insensitive, and assigning to
    # $scene would cast the hashtable into the typed [string]$Scene parameter.
    $spec = $jsScenes[$name]
    if ($spec.Fixture -and -not (Test-Path $spec.Fixture)) {
        if (-not $runAll) { throw "missing fixture for $name : $($spec.Fixture)" }
        Write-Host "[SKIP] $name (missing $($spec.Fixture))"
        continue
    }
    $patchyExe = Join-Path $buildDir 'patchy.exe'
    if (-not (Test-Path $patchyExe)) { throw "missing $patchyExe (run without -SkipBuild)" }

    # Publish only freshly generated output. Failed runs leave the last good image.
    $scratch = Join-Path $buildDir "readme-shot-$name"
    New-Item -ItemType Directory -Force $scratch | Out-Null
    $png = Join-Path $scratch "$name.png"
    foreach ($suffix in @('', '.base.png', '.dialog.png')) {
        $generated = "$png$suffix"
        if (Test-Path -LiteralPath $generated) { Remove-Item -LiteralPath $generated }
    }
    $scriptOut = Join-Path $buildDir "readme-shot-$name.txt"
    Remove-Item $scriptOut -ErrorAction SilentlyContinue

    $envNames = @('PATCHY_NO_SINGLE_INSTANCE', 'PATCHY_NO_SOUND', 'PATCHY_SETTINGS_DIR', 'QT_ENABLE_HIGHDPI_SCALING', 'QT_FONT_DPI', 'QT_QPA_PLATFORM', 'PATCHY_8BF_DIALOG_SETTLE_MS', 'PATCHY_8BF_ACCEPT_CLICK')
    $savedEnv = @{}
    foreach ($envName in $envNames) { $savedEnv[$envName] = [Environment]::GetEnvironmentVariable($envName, 'Process') }
    $env:PATCHY_NO_SINGLE_INSTANCE = '1'
    $env:PATCHY_NO_SOUND = '1'
    $env:PATCHY_SETTINGS_DIR = Join-Path $scratch ('settings-' + [guid]::NewGuid().ToString('N'))
    $env:QT_ENABLE_HIGHDPI_SCALING = '0'
    $env:QT_FONT_DPI = '96'
    Remove-Item Env:QT_QPA_PLATFORM -ErrorAction SilentlyContinue
    $proc = $null
    try {
        $argList = @('--run-script', $spec.Script, '--script-output', $scriptOut, '--script-arg', "out=$png")
        foreach ($extra in $spec.Args) { $argList += @('--script-arg', $extra) }
        if ($spec.Legacy) {
            # An installed copy wins duplicate plug-in IDs during scanning. Give
            # this capture its own portable host so it uses only its fixture copy.
            $hostDir = Join-Path $scratch ('host-' + [guid]::NewGuid().ToString('N'))
            New-Item -ItemType Directory -Force (Join-Path $hostDir 'plugins') | Out-Null
            foreach ($binary in @('patchy.exe', 'patchy-8bf-host32.exe', 'patchy-8bf-host64.exe')) {
                Copy-Item -LiteralPath (Join-Path $buildDir $binary) -Destination $hostDir
            }
            Get-ChildItem -LiteralPath $buildDir -Filter '*.dll' | Copy-Item -Destination $hostDir
            foreach ($folder in @('platforms', 'imageformats', 'styles')) {
                $source = Join-Path $buildDir $folder
                if (Test-Path -LiteralPath $source) { Copy-Item -LiteralPath $source -Destination $hostDir -Recurse }
            }
            $patchyExe = Join-Path $hostDir 'patchy.exe'
            $pluginCopy = Join-Path $hostDir 'plugins\KPT5'
            Copy-Item -LiteralPath $spec.Fixture -Destination $pluginCopy -Recurse
            $settingsFolder = Join-Path $env:PATCHY_SETTINGS_DIR 'Patchy'
            New-Item -ItemType Directory -Force $settingsFolder | Out-Null
            Set-Content -LiteralPath (Join-Path $settingsFolder 'Patchy.ini') -Value "[plugins]`nscreenSize=1024x768`n[preferences]`ncolorScheme=dark" -Encoding UTF8
            $env:PATCHY_8BF_DIALOG_SETTLE_MS = '5000'
            $env:PATCHY_8BF_ACCEPT_CLICK = '30,30'
            $argList += @('--script-arg', "plugins=$pluginCopy")
        }
        # ProcessStartInfo on Windows needs quoted tokens, including paths with spaces.
        $quotedArgs = $argList | ForEach-Object { '"' + ($_ -replace '(\\*)"', '$1$1\"' -replace '(\\+)$', '$1$1') + '"' }
        $proc = Start-Process -FilePath $patchyExe -ArgumentList $quotedArgs -WindowStyle Hidden -PassThru
        if (-not $proc.WaitForExit(180000)) {
            throw "$name scene timed out"
        }
    } finally {
        if ($proc -and -not $proc.HasExited) {
            # Only this run's helper processes, from this run's executable folder.
            $ownedFolder = Split-Path -Parent $patchyExe
            $helpers = @(Get-CimInstance Win32_Process -Filter "ParentProcessId=$($proc.Id)" |
                Where-Object {
                    $_.Name -match '^patchy-8bf-host(32|64)\.exe$' -and
                    $_.ExecutablePath -eq (Join-Path $ownedFolder $_.Name)
                })
            foreach ($helper in $helpers) { Stop-Process -Id $helper.ProcessId -ErrorAction SilentlyContinue }
            if (-not $proc.HasExited) { $proc.Kill() }
        }
        foreach ($envName in $envNames) { [Environment]::SetEnvironmentVariable($envName, $savedEnv[$envName], 'Process') }
    }

    $log = if (Test-Path $scriptOut) { Get-Content $scriptOut -Raw } else { '' }
    if ($proc.ExitCode -ne 0 -or $log -notmatch '\[done\]') {
        throw "$name scene failed (exit $($proc.ExitCode)): $log"
    }
    if ($spec.Legacy) {
        Add-Type -AssemblyName System.Drawing
        $base = [System.Drawing.Bitmap]::FromFile("$png.base.png")
        $dialog = [System.Drawing.Bitmap]::FromFile("$png.dialog.png")
        try {
            if ($dialog.Width -lt 600 -or $dialog.Height -lt 400) { throw 'Captured a KPT stub, not its full interface' }
            $g = [System.Drawing.Graphics]::FromImage($base)
            try {
                $scale = [Math]::Min(1.0, [Math]::Min(1040.0 / $dialog.Width, 800.0 / $dialog.Height))
                $w = [int]($dialog.Width * $scale); $h = [int]($dialog.Height * $scale)
                $x = $base.Width - $w - 18; $y = $base.Height - $h - 42
                $shadow = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(70, 0, 0, 0))
                try { $g.FillRectangle($shadow, $x - 6, $y + 6, $w + 12, $h + 6) } finally { $shadow.Dispose() }
                $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
                $g.DrawImage($dialog, $x, $y, $w, $h)
            } finally { $g.Dispose() }
            $base.Save($png, [System.Drawing.Imaging.ImageFormat]::Png)
        } finally { $dialog.Dispose(); $base.Dispose() }
    }
    if (-not (Test-Path $png)) { throw "$name scene reported done but wrote no $png" }
    Set-RoundedWindowCorners -Path $png
    $destination = Join-Path $outDir "$name.png"
    Copy-Item -LiteralPath $png -Destination $destination -Force
    Write-Host "updated $destination"
}
