using System.Text;
using XRay.Psd.Resources;
using XRay.Psd.Tests.Support;

namespace XRay.Psd.Tests;

public sealed class ResourceTests
{
    [Fact]
    public void Photoshop_resources_parse_into_typed_views()
    {
        var resources = Fixtures.Load("arrows.psd").Resources;

        Assert.Equal(new PsdResolutionInfo(72, PsdResolutionUnit.PixelsPerInch, PsdDimensionUnit.Inches, 72, PsdResolutionUnit.PixelsPerInch, PsdDimensionUnit.Inches), resources.Resolution);
        Assert.Equal(1.0, resources.PixelAspectRatio);
        Assert.Equal(new PsdPrintScale(PsdPrintScaleStyle.Centered, 0, 0, 1), resources.PrintScale);

        var grid = resources.GridAndGuides;
        Assert.NotNull(grid);
        Assert.Equal((18.0, 18.0), (grid.HorizontalGridCycle, grid.VerticalGridCycle));
        Assert.Empty(grid.Guides);

        var thumbnail = resources.Thumbnail;
        Assert.NotNull(thumbnail);
        Assert.Equal((PsdThumbnailFormat.Jpeg, 160, 114, 480, 24, false), (thumbnail.Format, thumbnail.Width, thumbnail.Height, thumbnail.RowBytes, thumbnail.BitsPerPixel, thumbnail.IsBgr));
        Assert.Equal(1692, thumbnail.Data.Length);
        Assert.True(thumbnail.Data.Span.StartsWith(new byte[] { 0xFF, 0xD8, 0xFF }));

        Assert.Equal(new PsdVersionInfo(1, true, "Adobe Photoshop", "Adobe Photoshop CS4", 1), resources.VersionInfo);

        var icc = resources.IccProfile;
        Assert.NotNull(icc);
        Assert.Equal(("sRGB IEC61966-2.1", "RGB ", "mntr", new Version(2, 1), 3144), (icc.Description, icc.ColorSpace, icc.DeviceClass, icc.Version, icc.Data.Length));

        var slices = resources.Slices;
        Assert.NotNull(slices);
        Assert.Equal((6, new PsdRect(0, 0, 486, 346), "arrows"), (slices.Version, slices.Bounds, slices.GroupName));
        var slice = Assert.Single(slices.Slices);
        Assert.Equal((PsdSliceOrigin.AutoGenerated, PsdSliceType.Image, new PsdRect(0, 0, 486, 346)), (slice.Origin, slice.Type, slice.Bounds));

        Assert.Equal(["Transparency"], resources.ChannelNames);
        Assert.Contains("x:xmpmeta", resources.Xmp, StringComparison.Ordinal);
        var iptc = Assert.Single(resources.Iptc);
        Assert.Equal((2, 0, 2), (iptc.Record, iptc.DataSet, iptc.Value.Length));
        Assert.Null(resources.LayerComps);
    }

    [Fact]
    public void Version_info_agrees_with_the_merged_image_flag()
    {
        var document = Fixtures.Load("photoshop-basic.psb");

        var info = document.Resources.VersionInfo;
        Assert.NotNull(info);
        Assert.False(info.HasRealMergedData);
        Assert.False(document.HasRealMergedImage);
        Assert.Equal("Adobe Photoshop 2026", info.ReaderName);
    }

    [Fact]
    public void Typed_views_are_cached()
    {
        var document = Fixtures.Load("arrows.psd");

        Assert.Same(document.Resources, document.Resources);
        Assert.Same(document.Resources.Slices, document.Resources.Slices);
        Assert.Same(document.Resources.Thumbnail, document.Resources.Thumbnail);
    }

    [Fact]
    public void Synthetic_resources_cover_units_guides_comps_and_metadata()
    {
        var builder = new PsdBuilder();
        builder.Resources.Add((ImageResourceIds.ResolutionInfo, string.Empty, Resolution(150, 2, 2, 300.5, 1, 3)));
        builder.Resources.Add((ImageResourceIds.GridAndGuides, string.Empty, Guides(320, 0, (64, 1), (-16, 0), (100, 0))));
        builder.Resources.Add((ImageResourceIds.ThumbnailLegacy, string.Empty, RawThumbnail()));
        builder.Resources.Add((ImageResourceIds.LayerComps, string.Empty, LayerComps()));
        builder.Resources.Add((ImageResourceIds.PrintScale, string.Empty, PrintScale(2, 10.5f, -3, 0.5f)));
        builder.Resources.Add((ImageResourceIds.PixelAspectRatio, string.Empty, AspectRatio(0.9)));
        builder.Resources.Add((ImageResourceIds.IptcNaa, string.Empty, Iptc((2, 120, Encoding.UTF8.GetBytes("Café caption")), (2, 25, [0x4E, 0xE9]))));
        builder.Resources.Add((ImageResourceIds.Xmp, string.Empty, Encoding.UTF8.GetBytes("<x:xmpmeta xmlns:x=\"adobe:ns:meta/\"/>\0")));
        builder.Resources.Add((ImageResourceIds.Slices, string.Empty, SlicesV6()));
        var resources = PsdDocument.Load(builder.Build()).Resources;

        Assert.Equal(new PsdResolutionInfo(150, PsdResolutionUnit.PixelsPerCentimeter, PsdDimensionUnit.Centimeters, 300.5, PsdResolutionUnit.PixelsPerInch, PsdDimensionUnit.Points), resources.Resolution);

        var grid = resources.GridAndGuides;
        Assert.NotNull(grid);
        Assert.Equal(10, grid.HorizontalGridCycle);
        Assert.Equal(18, grid.VerticalGridCycle); // 0 reads as the default 576/32
        Assert.Equal([new(2, PsdGuideOrientation.Horizontal), new(-0.5, PsdGuideOrientation.Vertical), new(3.125, PsdGuideOrientation.Vertical)], grid.Guides);

        var thumbnail = resources.Thumbnail;
        Assert.NotNull(thumbnail);
        Assert.Equal((PsdThumbnailFormat.RawRgb, 2, 1, 8, true), (thumbnail.Format, thumbnail.Width, thumbnail.Height, thumbnail.RowBytes, thumbnail.IsBgr));
        Assert.Equal(8, thumbnail.Data.Length);

        var comps = resources.LayerComps;
        Assert.NotNull(comps);
        Assert.Equal([new PsdLayerComp(7, "Day", "Bright", true, false, true), new PsdLayerComp(9, "Night", string.Empty, false, true, false)], comps.Comps);
        Assert.Equal(9, comps.LastAppliedCompId);

        Assert.Equal(new PsdPrintScale(PsdPrintScaleStyle.UserDefined, 10.5f, -3, 0.5f), resources.PrintScale);
        Assert.Equal(0.9, resources.PixelAspectRatio);
        Assert.Equal(["Café caption", "Né"], resources.Iptc.Select(d => d.Text));
        Assert.Equal("<x:xmpmeta xmlns:x=\"adobe:ns:meta/\"/>", resources.Xmp);

        var slices = resources.Slices;
        Assert.NotNull(slices);
        Assert.Equal("group", slices.GroupName);
        Assert.Collection(
            slices.Slices,
            s =>
            {
                Assert.Equal((5, PsdSliceOrigin.LayerBased, 42, "hero"), (s.Id, s.Origin, s.AssociatedLayerId, s.Name));
                Assert.Equal(new PsdRect(1, 2, 3, 4), s.Bounds);
                Assert.Equal(("https://example.com", "_blank", "msg", "alt", true, "<b>cell</b>"), (s.Url, s.Target, s.Message, s.AltTag, s.CellTextIsHtml, s.CellText));
                Assert.Equal(new PsdColor(10, 20, 30, 255), s.BackgroundColor);
            },
            s => Assert.Equal((6, PsdSliceOrigin.UserGenerated, "second", PsdSliceType.NoImage), (s.Id, s.Origin, s.Name, s.Type)));

        Assert.Null(resources.VersionInfo);
        Assert.Null(resources.IccProfile);
        Assert.Empty(resources.ChannelNames);
    }

    [Fact]
    public void Missing_or_damaged_resources_read_as_null()
    {
        Assert.All(Views(PsdDocument.Load(new PsdBuilder().Build()).Resources), Assert.Null);

        var builder = new PsdBuilder();
        builder.Resources.Add((ImageResourceIds.ResolutionInfo, string.Empty, new byte[8]));
        builder.Resources.Add((ImageResourceIds.GridAndGuides, string.Empty, Guides(2, 576, 576, (0, 0)))); // version 2
        builder.Resources.Add((ImageResourceIds.Thumbnail, string.Empty, new byte[28]));
        builder.Resources.Add((ImageResourceIds.LayerComps, string.Empty, [0, 0, 0, 15, 1, 2]));
        builder.Resources.Add((ImageResourceIds.PrintScale, string.Empty, new byte[5]));
        builder.Resources.Add((ImageResourceIds.PixelAspectRatio, string.Empty, AspectRatio(double.NaN)));
        builder.Resources.Add((ImageResourceIds.VersionInfo, string.Empty, [0, 0, 0, 1, 1, 0xFF, 0xFF, 0xFF, 0xFF]));
        builder.Resources.Add((ImageResourceIds.Slices, string.Empty, [0, 0, 0, 9]));
        var resources = PsdDocument.Load(builder.Build()).Resources;

        Assert.All(Views(resources), Assert.Null);
        Assert.Empty(resources.Iptc);

        // A guide count larger than the payload is rejected rather than allocated.
        var guides = new PsdBuilder();
        var payload = Guides(1, 576, 576);
        payload[15] = 0xFF;
        payload[14] = 0xFF;
        guides.Resources.Add((ImageResourceIds.GridAndGuides, string.Empty, payload));
        Assert.Null(PsdDocument.Load(guides.Build()).Resources.GridAndGuides);
    }

    private static object?[] Views(PsdImageResources r) =>
        [r.Resolution, r.GridAndGuides, r.Thumbnail, r.Slices, r.LayerComps, r.PrintScale, r.PixelAspectRatio, r.VersionInfo, r.IccProfile, r.Xmp];

    private static byte[] Resolution(double h, ushort hUnit, ushort wUnit, double v, ushort vUnit, ushort heightUnit)
    {
        var w = new PsdBuilder.Writer();
        w.U32((uint)Math.Round(h * 65536));
        w.U16(hUnit);
        w.U16(wUnit);
        w.U32((uint)Math.Round(v * 65536));
        w.U16(vUnit);
        w.U16(heightUnit);
        return w.ToArray();
    }

    private static byte[] Guides(int horizontalCycle, int verticalCycle, params (int Position32, byte Direction)[] guides) =>
        Guides(1, horizontalCycle, verticalCycle, guides);

    private static byte[] Guides(uint version, int horizontalCycle, int verticalCycle, params (int Position32, byte Direction)[] guides)
    {
        var w = new PsdBuilder.Writer();
        w.U32(version);
        w.I32(horizontalCycle);
        w.I32(verticalCycle);
        w.U32((uint)guides.Length);
        foreach (var (position, direction) in guides)
        {
            w.I32(position);
            w.U8(direction);
        }

        return w.ToArray();
    }

    private static byte[] RawThumbnail()
    {
        var w = new PsdBuilder.Writer();
        w.U32(0); // raw
        w.U32(2);
        w.U32(1);
        w.U32(8); // row bytes padded to 4
        w.U32(8);
        w.U32(0);
        w.U16(24);
        w.U16(1);
        w.Bytes([1, 2, 3, 4, 5, 6, 0, 0]);
        return w.ToArray();
    }

    private static byte[] PrintScale(ushort style, float x, float y, float scale)
    {
        var w = new PsdBuilder.Writer();
        w.U16(style);
        w.U32(BitConverter.SingleToUInt32Bits(x));
        w.U32(BitConverter.SingleToUInt32Bits(y));
        w.U32(BitConverter.SingleToUInt32Bits(scale));
        return w.ToArray();
    }

    private static byte[] AspectRatio(double ratio)
    {
        var w = new PsdBuilder.Writer();
        w.U32(2);
        w.F64(ratio);
        return w.ToArray();
    }

    private static byte[] Iptc(params (byte Record, byte DataSet, byte[] Value)[] dataSets)
    {
        var w = new PsdBuilder.Writer();
        foreach (var (record, dataSet, value) in dataSets)
        {
            w.U8(0x1C);
            w.U8(record);
            w.U8(dataSet);
            w.U16((ushort)value.Length);
            w.Bytes(value);
        }

        return w.ToArray();
    }

    private static byte[] LayerComps()
    {
        var w = new PsdBuilder.Writer();
        w.U32(16);
        DescriptorHeader(w, "null", 2);
        w.DescriptorId("list");
        w.Ascii("VlLs");
        w.U32(2);
        Comp(w, "Day", "Bright", 7, 5);
        Comp(w, "Night", null, 9, 2);
        w.DescriptorId("lastAppliedComp");
        w.Ascii("long");
        w.I32(9);
        return w.ToArray();

        static void Comp(PsdBuilder.Writer w, string name, string? comment, int id, int captured)
        {
            w.Ascii("Objc");
            DescriptorHeader(w, "Comp", comment is null ? 3 : 4);
            w.DescriptorId("Nm  ");
            w.Ascii("TEXT");
            w.UnicodeString(name);
            if (comment is not null)
            {
                w.DescriptorId("comment");
                w.Ascii("TEXT");
                w.UnicodeString(comment);
            }

            w.DescriptorId("compID");
            w.Ascii("long");
            w.I32(id);
            w.DescriptorId("capturedInfo");
            w.Ascii("long");
            w.I32(captured);
        }
    }

    private static void DescriptorHeader(PsdBuilder.Writer w, string classId, int count)
    {
        w.UnicodeString(string.Empty);
        w.DescriptorId(classId);
        w.U32((uint)count);
    }

    private static byte[] SlicesV6()
    {
        var w = new PsdBuilder.Writer();
        w.U32(6);
        w.I32(0); // top, left, bottom, right
        w.I32(0);
        w.I32(4);
        w.I32(4);
        w.UnicodeString("group");
        w.U32(2);

        // A layer-based slice followed by the Photoshop 7 per-slice descriptor.
        w.I32(5);
        w.I32(0);
        w.U32(1);
        w.I32(42);
        w.UnicodeString("hero");
        w.U32(1);
        w.I32(1); // left, top, right, bottom
        w.I32(2);
        w.I32(3);
        w.I32(4);
        w.UnicodeString("https://example.com");
        w.UnicodeString("_blank");
        w.UnicodeString("msg");
        w.UnicodeString("alt");
        w.U8(1);
        w.UnicodeString("<b>cell</b>");
        w.I32(0);
        w.I32(0);
        w.Bytes([255, 10, 20, 30]); // ARGB
        w.U32(16);
        DescriptorHeader(w, "null", 1);
        w.DescriptorId("Nm  ");
        w.Ascii("TEXT");
        w.UnicodeString("ignored");

        // A user slice without a descriptor.
        w.I32(6);
        w.I32(0);
        w.U32(2);
        w.UnicodeString("second");
        w.U32(0);
        w.Zeros(16);
        for (var i = 0; i < 4; i++)
        {
            w.UnicodeString(string.Empty);
        }

        w.U8(0);
        w.UnicodeString(string.Empty);
        w.Zeros(12);
        return w.ToArray();
    }
}
